// Copyright 2024 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:developer' as developer;
import 'dart:math';

import 'package:agents_flutter/agents_flutter.dart';

import 'agent_run_scope.dart';

/// Field names for the durable per-model-call usage ledger.
abstract final class UsageRecords {
  /// The [RecordStore] collection holding usage records.
  static const String collection = 'usage_records';

  /// The conversation the model call belonged to.
  static const String conversationIdField = 'conversationId';

  /// The session (model-context epoch) active during the call.
  static const String sessionIdField = 'sessionId';

  /// ISO-8601 UTC timestamp of when the call completed.
  static const String timestampField = 'timestamp';

  /// The provider's model identifier.
  static const String modelIdField = 'modelId';

  /// The configured model source the call went through.
  static const String sourceIdField = 'sourceId';

  /// The provider type name.
  static const String providerField = 'provider';

  /// Prompt tokens sent to the model.
  static const String inputField = 'input';

  /// Completion tokens generated by the model.
  static const String outputField = 'output';

  /// Total tokens reported by the provider.
  static const String totalField = 'total';

  /// Input tokens served from the provider's cache.
  static const String cachedField = 'cached';

  /// Tokens spent on reasoning/thinking.
  static const String reasoningField = 'reasoning';

  /// The saved agent whose run made the call, when the call was scoped to
  /// an [AgentRunScope].
  ///
  /// Absent on rows written by scope-less callers (hosting internals, the
  /// title summarizer), which belong to no agent.
  static const String agentIdField = 'agentId';

  /// The [AgentRunRecord] the call belonged to, when a run was in flight.
  ///
  /// This is the join key: run-level token totals are the sum of the usage
  /// rows carrying the run's id. Tokens are deliberately not duplicated
  /// onto the run record itself.
  static const String runIdField = 'runId';
}

/// Accumulated token totals for one model within a set of usage records.
class ModelUsageTotals {
  ModelUsageTotals._(this.modelId, this.provider);

  /// The provider's model identifier.
  final String modelId;

  /// The provider type name.
  final String provider;

  /// Number of model calls contributing to these totals.
  int calls = 0;

  /// Summed prompt tokens.
  int inputTokens = 0;

  /// Summed completion tokens.
  int outputTokens = 0;

  /// Summed cache-served prompt tokens.
  int cachedTokens = 0;

  /// Summed reasoning tokens.
  int reasoningTokens = 0;

  void _add(ChatUsageRecord record) {
    calls++;
    inputTokens += record.inputTokenCount ?? 0;
    outputTokens += record.outputTokenCount ?? 0;
    cachedTokens += record.cachedInputTokenCount ?? 0;
    reasoningTokens += record.reasoningTokenCount ?? 0;
  }
}

/// A durable ledger of every model call's token usage, one record per call.
///
/// Implements [UsageRecordSink] so `UsageTrackingChatClient` can report
/// directly into it. Records are written fire-and-forget: usage bookkeeping
/// must never block or fail a model response.
class UsageStore implements UsageRecordSink {
  /// Creates a [UsageStore] over [records].
  UsageStore(this._records);

  final RecordStore _records;

  @override
  void record(ChatUsageRecord record) => recordAttributed(record);

  /// Returns a sink that stamps [scope]'s agent and current run onto every
  /// record it forwards here.
  ///
  /// The package builds [ChatUsageRecord] itself with a fixed field set, so
  /// the attribution cannot ride along on the record — it is applied at the
  /// sink, which is the last app-owned point before the write.
  UsageRecordSink attributedTo(AgentRunScope scope) =>
      _RunAttributingUsageSink(this, scope);

  /// Writes [record], optionally attributed to [agentId] and [runId].
  void recordAttributed(
    ChatUsageRecord record, {
    String? agentId,
    String? runId,
  }) {
    unawaited(
      _records
          .put(UsageRecords.collection, _newRecordId(), {
            UsageRecords.agentIdField: ?agentId,
            UsageRecords.runIdField: ?runId,
            if (record.conversationId != null)
              UsageRecords.conversationIdField: record.conversationId,
            if (record.sessionId != null)
              UsageRecords.sessionIdField: record.sessionId,
            UsageRecords.timestampField: record.timestamp
                .toUtc()
                .toIso8601String(),
            UsageRecords.modelIdField: record.modelId,
            UsageRecords.sourceIdField: record.sourceId,
            UsageRecords.providerField: record.provider,
            if (record.inputTokenCount != null)
              UsageRecords.inputField: record.inputTokenCount,
            if (record.outputTokenCount != null)
              UsageRecords.outputField: record.outputTokenCount,
            if (record.totalTokenCount != null)
              UsageRecords.totalField: record.totalTokenCount,
            if (record.cachedInputTokenCount != null)
              UsageRecords.cachedField: record.cachedInputTokenCount,
            if (record.reasoningTokenCount != null)
              UsageRecords.reasoningField: record.reasoningTokenCount,
          })
          .catchError((Object e, StackTrace s) {
            developer.log(
              'Failed to persist usage record.',
              name: 'agents_app.usage',
              error: e,
              stackTrace: s,
            );
          }),
    );
  }

  /// Loads the usage records of [conversationId] in call order.
  Future<List<ChatUsageRecord>> listFor(String conversationId) async {
    final records = await _records.query(
      UsageRecords.collection,
      query: _forConversation(conversationId),
    );
    return [for (final record in records) _decode(record.value)];
  }

  /// Watches the usage records of [conversationId] in call order.
  Stream<List<ChatUsageRecord>> watchFor(String conversationId) => _records
      .watch(UsageRecords.collection, query: _forConversation(conversationId))
      .map((records) => [for (final record in records) _decode(record.value)]);

  /// Deletes the usage ledger of [conversationId].
  Future<void> deleteFor(String conversationId) => _records.deleteWhere(
    UsageRecords.collection,
    RecordQuery(equals: {UsageRecords.conversationIdField: conversationId}),
  );

  /// Groups [records] into per-model totals, optionally keeping only the
  /// records of [sessionId].
  static Map<String, ModelUsageTotals> totalsByModel(
    Iterable<ChatUsageRecord> records, {
    String? sessionId,
  }) {
    final totals = <String, ModelUsageTotals>{};
    for (final record in records) {
      if (sessionId != null && record.sessionId != sessionId) continue;
      totals
          .putIfAbsent(
            record.modelId,
            () => ModelUsageTotals._(record.modelId, record.provider),
          )
          ._add(record);
    }
    return totals;
  }

  /// Sums the tokens of every model call made during [runId].
  ///
  /// This is the run's token total. It is computed rather than stored so
  /// there is exactly one place tokens are counted.
  Future<TokenTotals> totalsForRun(String runId) async {
    final records = await _records.query(
      UsageRecords.collection,
      query: RecordQuery(equals: {UsageRecords.runIdField: runId}),
    );
    return TokenTotals._sum(records.map((record) => record.value));
  }

  /// Sums tokens per agent across every attributed usage record.
  ///
  /// Rows written by scope-less callers carry no agent id and are skipped,
  /// so hosting internals and the title summarizer do not skew per-agent
  /// rollups.
  Future<Map<String, TokenTotals>> totalsByAgent({DateTime? since}) async {
    final records = await _records.query(UsageRecords.collection);
    final cutoff = since?.toUtc();
    final grouped = <String, List<Map<String, Object?>>>{};
    for (final record in records) {
      final agentId = record.value[UsageRecords.agentIdField] as String?;
      if (agentId == null) continue;
      if (cutoff != null) {
        final at = DateTime.tryParse(
          record.value[UsageRecords.timestampField] as String? ?? '',
        );
        if (at == null || at.isBefore(cutoff)) continue;
      }
      grouped.putIfAbsent(agentId, () => []).add(record.value);
    }
    return {
      for (final entry in grouped.entries)
        entry.key: TokenTotals._sum(entry.value),
    };
  }

  /// Returns attributed usage rows at or after [since], in call order, as
  /// bare `(timestamp, input, output)` points.
  ///
  /// The token time series on the Overview needs a slice across all
  /// conversations, which neither the per-conversation readers nor the
  /// per-agent rollup provides. Rows without an agent id (hosting
  /// internals, the title summarizer) are excluded so the series matches
  /// the per-agent charts beside it. Pass [agentId] to restrict the slice
  /// to one agent — a per-agent chart must not sum in everyone's tokens.
  Future<List<UsageTokenPoint>> tokenPointsSince(
    DateTime since, {
    String? agentId,
  }) async {
    final records = await _records.query(UsageRecords.collection);
    final cutoff = since.toUtc();
    final points = <UsageTokenPoint>[];
    for (final record in records) {
      final rowAgent = record.value[UsageRecords.agentIdField] as String?;
      if (rowAgent == null) continue;
      if (agentId != null && rowAgent != agentId) continue;
      final at = DateTime.tryParse(
        record.value[UsageRecords.timestampField] as String? ?? '',
      );
      if (at == null || at.isBefore(cutoff)) continue;
      points.add(
        UsageTokenPoint(
          at: at.toLocal(),
          input: record.value[UsageRecords.inputField] as int? ?? 0,
          output: record.value[UsageRecords.outputField] as int? ?? 0,
        ),
      );
    }
    points.sort((a, b) => a.at.compareTo(b.at));
    return points;
  }

  static RecordQuery _forConversation(String conversationId) => RecordQuery(
    equals: {UsageRecords.conversationIdField: conversationId},
    orderBy: UsageRecords.timestampField,
  );

  static ChatUsageRecord _decode(Map<String, Object?> value) => ChatUsageRecord(
    timestamp:
        DateTime.tryParse(
          value[UsageRecords.timestampField] as String? ?? '',
        ) ??
        DateTime.fromMillisecondsSinceEpoch(0),
    conversationId: value[UsageRecords.conversationIdField] as String?,
    sessionId: value[UsageRecords.sessionIdField] as String?,
    modelId: value[UsageRecords.modelIdField] as String? ?? 'unknown',
    sourceId: value[UsageRecords.sourceIdField] as String? ?? 'unknown',
    provider: value[UsageRecords.providerField] as String? ?? 'unknown',
    inputTokenCount: value[UsageRecords.inputField] as int?,
    outputTokenCount: value[UsageRecords.outputField] as int?,
    totalTokenCount: value[UsageRecords.totalField] as int?,
    cachedInputTokenCount: value[UsageRecords.cachedField] as int?,
    reasoningTokenCount: value[UsageRecords.reasoningField] as int?,
  );

  static final Random _random = Random.secure();

  static String _newRecordId() {
    final suffix = List.generate(
      16,
      (_) => _random.nextInt(16).toRadixString(16),
    ).join();
    return '${DateTime.now().microsecondsSinceEpoch}-$suffix';
  }
}

/// One model call's token counts at a point in time.
///
/// The timestamp is local, ready to bucket for the token time series.
class UsageTokenPoint {
  /// Creates a [UsageTokenPoint].
  const UsageTokenPoint({
    required this.at,
    required this.input,
    required this.output,
  });

  /// When the call completed, in local time.
  final DateTime at;

  /// Prompt tokens.
  final int input;

  /// Completion tokens.
  final int output;
}

/// Accumulated token counts over a set of usage records.
class TokenTotals {
  /// Creates [TokenTotals].
  const TokenTotals({
    this.calls = 0,
    this.inputTokens = 0,
    this.outputTokens = 0,
    this.cachedTokens = 0,
    this.reasoningTokens = 0,
  });

  /// Model calls contributing to these totals.
  final int calls;

  /// Summed prompt tokens.
  final int inputTokens;

  /// Summed completion tokens.
  final int outputTokens;

  /// Summed cache-served prompt tokens.
  final int cachedTokens;

  /// Summed reasoning tokens.
  final int reasoningTokens;

  /// Prompt plus completion tokens.
  int get totalTokens => inputTokens + outputTokens;

  static TokenTotals _sum(Iterable<Map<String, Object?>> values) {
    var calls = 0;
    var input = 0;
    var output = 0;
    var cached = 0;
    var reasoning = 0;
    for (final value in values) {
      calls++;
      input += value[UsageRecords.inputField] as int? ?? 0;
      output += value[UsageRecords.outputField] as int? ?? 0;
      cached += value[UsageRecords.cachedField] as int? ?? 0;
      reasoning += value[UsageRecords.reasoningField] as int? ?? 0;
    }
    return TokenTotals(
      calls: calls,
      inputTokens: input,
      outputTokens: output,
      cachedTokens: cached,
      reasoningTokens: reasoning,
    );
  }
}

/// Forwards records to a [UsageStore], stamping the scope's agent and the
/// run in flight at the moment each record is written.
///
/// The run id is read through [AgentRunScope.runIdResolver] rather than
/// captured at construction because one scope serves many runs: a chat
/// scope is built when the conversation opens and then handles every
/// subsequent turn.
class _RunAttributingUsageSink implements UsageRecordSink {
  _RunAttributingUsageSink(this._store, this._scope);

  final UsageStore _store;
  final AgentRunScope _scope;

  @override
  void record(ChatUsageRecord record) => _store.recordAttributed(
    record,
    agentId: _scope.agentId,
    runId: _scope.runIdResolver(),
  );
}

/// A [UsageRecordSink] that discards records.
///
/// Used for private conversations, which keep in-memory per-message badges
/// but must not write a durable ledger.
class DiscardingUsageRecordSink implements UsageRecordSink {
  /// Creates a discarding sink.
  const DiscardingUsageRecordSink();

  @override
  void record(ChatUsageRecord record) {}
}
