// Copyright 2024 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:developer' as developer;
import 'dart:math';

import 'package:agents_flutter/agents_flutter.dart';

/// Field names for the durable per-model-call usage ledger.
abstract final class UsageRecords {
  /// The [RecordStore] collection holding usage records.
  static const String collection = 'usage_records';

  /// The conversation the model call belonged to.
  static const String conversationIdField = 'conversationId';

  /// The session (model-context epoch) active during the call.
  static const String sessionIdField = 'sessionId';

  /// ISO-8601 UTC timestamp of when the call completed.
  static const String timestampField = 'timestamp';

  /// The provider's model identifier.
  static const String modelIdField = 'modelId';

  /// The configured model source the call went through.
  static const String sourceIdField = 'sourceId';

  /// The provider type name.
  static const String providerField = 'provider';

  /// Prompt tokens sent to the model.
  static const String inputField = 'input';

  /// Completion tokens generated by the model.
  static const String outputField = 'output';

  /// Total tokens reported by the provider.
  static const String totalField = 'total';

  /// Input tokens served from the provider's cache.
  static const String cachedField = 'cached';

  /// Tokens spent on reasoning/thinking.
  static const String reasoningField = 'reasoning';
}

/// Accumulated token totals for one model within a set of usage records.
class ModelUsageTotals {
  ModelUsageTotals._(this.modelId, this.provider);

  /// The provider's model identifier.
  final String modelId;

  /// The provider type name.
  final String provider;

  /// Number of model calls contributing to these totals.
  int calls = 0;

  /// Summed prompt tokens.
  int inputTokens = 0;

  /// Summed completion tokens.
  int outputTokens = 0;

  /// Summed cache-served prompt tokens.
  int cachedTokens = 0;

  /// Summed reasoning tokens.
  int reasoningTokens = 0;

  void _add(ChatUsageRecord record) {
    calls++;
    inputTokens += record.inputTokenCount ?? 0;
    outputTokens += record.outputTokenCount ?? 0;
    cachedTokens += record.cachedInputTokenCount ?? 0;
    reasoningTokens += record.reasoningTokenCount ?? 0;
  }
}

/// A durable ledger of every model call's token usage, one record per call.
///
/// Implements [UsageRecordSink] so `UsageTrackingChatClient` can report
/// directly into it. Records are written fire-and-forget: usage bookkeeping
/// must never block or fail a model response.
class UsageStore implements UsageRecordSink {
  /// Creates a [UsageStore] over [records].
  UsageStore(this._records);

  final RecordStore _records;

  @override
  void record(ChatUsageRecord record) {
    unawaited(
      _records
          .put(UsageRecords.collection, _newRecordId(), {
            if (record.conversationId != null)
              UsageRecords.conversationIdField: record.conversationId,
            if (record.sessionId != null)
              UsageRecords.sessionIdField: record.sessionId,
            UsageRecords.timestampField: record.timestamp
                .toUtc()
                .toIso8601String(),
            UsageRecords.modelIdField: record.modelId,
            UsageRecords.sourceIdField: record.sourceId,
            UsageRecords.providerField: record.provider,
            if (record.inputTokenCount != null)
              UsageRecords.inputField: record.inputTokenCount,
            if (record.outputTokenCount != null)
              UsageRecords.outputField: record.outputTokenCount,
            if (record.totalTokenCount != null)
              UsageRecords.totalField: record.totalTokenCount,
            if (record.cachedInputTokenCount != null)
              UsageRecords.cachedField: record.cachedInputTokenCount,
            if (record.reasoningTokenCount != null)
              UsageRecords.reasoningField: record.reasoningTokenCount,
          })
          .catchError((Object e, StackTrace s) {
            developer.log(
              'Failed to persist usage record.',
              name: 'agents_app.usage',
              error: e,
              stackTrace: s,
            );
          }),
    );
  }

  /// Loads the usage records of [conversationId] in call order.
  Future<List<ChatUsageRecord>> listFor(String conversationId) async {
    final records = await _records.query(
      UsageRecords.collection,
      query: _forConversation(conversationId),
    );
    return [for (final record in records) _decode(record.value)];
  }

  /// Watches the usage records of [conversationId] in call order.
  Stream<List<ChatUsageRecord>> watchFor(String conversationId) => _records
      .watch(UsageRecords.collection, query: _forConversation(conversationId))
      .map((records) => [for (final record in records) _decode(record.value)]);

  /// Deletes the usage ledger of [conversationId].
  Future<void> deleteFor(String conversationId) => _records.deleteWhere(
    UsageRecords.collection,
    RecordQuery(equals: {UsageRecords.conversationIdField: conversationId}),
  );

  /// Groups [records] into per-model totals, optionally keeping only the
  /// records of [sessionId].
  static Map<String, ModelUsageTotals> totalsByModel(
    Iterable<ChatUsageRecord> records, {
    String? sessionId,
  }) {
    final totals = <String, ModelUsageTotals>{};
    for (final record in records) {
      if (sessionId != null && record.sessionId != sessionId) continue;
      totals
          .putIfAbsent(
            record.modelId,
            () => ModelUsageTotals._(record.modelId, record.provider),
          )
          ._add(record);
    }
    return totals;
  }

  static RecordQuery _forConversation(String conversationId) => RecordQuery(
    equals: {UsageRecords.conversationIdField: conversationId},
    orderBy: UsageRecords.timestampField,
  );

  static ChatUsageRecord _decode(Map<String, Object?> value) => ChatUsageRecord(
    timestamp:
        DateTime.tryParse(
          value[UsageRecords.timestampField] as String? ?? '',
        ) ??
        DateTime.fromMillisecondsSinceEpoch(0),
    conversationId: value[UsageRecords.conversationIdField] as String?,
    sessionId: value[UsageRecords.sessionIdField] as String?,
    modelId: value[UsageRecords.modelIdField] as String? ?? 'unknown',
    sourceId: value[UsageRecords.sourceIdField] as String? ?? 'unknown',
    provider: value[UsageRecords.providerField] as String? ?? 'unknown',
    inputTokenCount: value[UsageRecords.inputField] as int?,
    outputTokenCount: value[UsageRecords.outputField] as int?,
    totalTokenCount: value[UsageRecords.totalField] as int?,
    cachedInputTokenCount: value[UsageRecords.cachedField] as int?,
    reasoningTokenCount: value[UsageRecords.reasoningField] as int?,
  );

  static final Random _random = Random.secure();

  static String _newRecordId() {
    final suffix = List.generate(
      16,
      (_) => _random.nextInt(16).toRadixString(16),
    ).join();
    return '${DateTime.now().microsecondsSinceEpoch}-$suffix';
  }
}

/// A [UsageRecordSink] that discards records.
///
/// Used for private conversations, which keep in-memory per-message badges
/// but must not write a durable ledger.
class DiscardingUsageRecordSink implements UsageRecordSink {
  /// Creates a discarding sink.
  const DiscardingUsageRecordSink();

  @override
  void record(ChatUsageRecord record) {}
}
